//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedisUtils
{
    using System;

    public partial class userinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> count { get; set; }
        public string city { get; set; }

        public override string ToString()
        {
            return String.Format("id={0},name={1},city={2}", id, name, city);
        }
    }
}
